# Generated by Django 4.2 on 2024-03-05 08:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("content", "0002_details"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Details",
            new_name="Detail",
        ),
    ]
